name: 'Run tests from Qase'

on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: "Qase API URL"
        required: true
      qase_report:
        description: "Enabled/disabled reporting to Qase"
        required: true
      qase_project_code:
        description: "Qase project code"
        required: true
      qase_run_id:
        description: "Qase Run ID"
        required: true
      qase_run_complete:
        description: "Qase Run autocomplete"
        required: true

  # push:
  #   branches:
  #     - '*'
  #     - '*/*'
  #     - '**'
  #     - '!sponsors'
  # pull_request:
  #   branches:
  #     - '*'
  #     - '*/*'
  #     - '**'
  #     - '!sponsors'

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_TESTOPS_PROJECT: ${{ inputs.qase_project_code }}
  QASE_TESTOPS_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_TESTOPS_RUN_COMPLETE: true
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TOKEN }}
  QASE_MODE: 'testops'
  QASE_ROOT_SUITE: 'automation-demo'


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: cskmnrpt/qase-link-run@v2
        env:
          QASE_TESTOPS_API_TOKEN: ${{ env.QASE_TESTOPS_API_TOKEN }}

      - uses: actions/checkout@v4
        with:
          persist-credentials: true
            
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          
      - run: npm ci

      - run: npm run build

      - run: npm test

    #   - name: Run Server tests
    #     run: npm run test:node
    #     if: steps.changed-ignored.outputs.only_modified == 'false'
    #
    # # We run browser tests only on one version of the node, since client tests do not depend on the server environment.
    #   - name: Run browser tests
    #     run: npm run test:browser
    #     if: steps.changed-ignored.outputs.only_modified == 'false' && matrix.node-version == '22.x'
    #   - name: Run package tests
    #     run: npm run test:package
    #     if: steps.changed-ignored.outputs.only_modified == 'false'
